// Mocks generated by Mockito 5.3.2 from annotations
// in random_cat/test/presentation/bloc/cat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:random_cat/core/error/failure.dart' as _i6;
import 'package:random_cat/domain/entities/cat.dart' as _i7;
import 'package:random_cat/domain/repositories/cat_repositories.dart' as _i2;
import 'package:random_cat/domain/usecases/get_random_cat_image.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatRepositories_0 extends _i1.SmartFake
    implements _i2.CatRepositories {
  _FakeCatRepositories_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRandomCatImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomCatImage extends _i1.Mock implements _i4.GetRandomCatImage {
  MockGetRandomCatImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepositories get catRepositories => (super.noSuchMethod(
        Invocation.getter(#catRepositories),
        returnValue: _FakeCatRepositories_0(
          this,
          Invocation.getter(#catRepositories),
        ),
      ) as _i2.CatRepositories);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Cat>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Cat>>.value(
            _FakeEither_1<_i6.Failure, _i7.Cat>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Cat>>);
}
